### ISSUE TITLE
Could not find a matching account

### ISSUE THREAD

**Issue by latchee** [pelaxa/ff3-ofx#1]
Hi There,

I have just installed ff3-ofx alongside my Firefly iii appliation.
When I am trying to import an ofx file, I get the error "Could not find a matching account to process transactions"
From what I can see, my account number is specified in the file like this:
`<BANKACCTFROM>
<BANKID>12
<BRANCHID>1234
<ACCTID>1234567-12
<ACCTTYPE>CHECKING
</BANKACCTFROM>`
(I have obfuscated my real account number with dummy number).
The concatenation of BANKID, BRANCHID and ACCTID gives the same account number as in Firefly:
12-1234-1234567-12
Would you know why this importer is not able to match the account?

Kind regards,

**Comment by pelaxa** [comment]
Sorry folks, I had missed this somehow for all this time. 

Is it possible to provide an OFX file that has the account id specified this way?  By all means make them dummy numbers and just leave one dummy transaction in there but I need to see the full OFX structure to be able to provide a fix. 

All of my OFX files just have one field for account id.

**Comment by latchee** [comment]
Hi @pelaxa ,
No worries at all. Thank you for looking into this. Here is an extract, with dummy numbers, of the OFX file:

```
OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRSV1>
<SONRS>
<STATUS>
<CODE>0
<SEVERITY>INFO
</STATUS>
<DTSERVER>20240903130726
<LANGUAGE>ENG
</SONRS>
</SIGNONMSGSRSV1>
<BANKMSGSRSV1>
<STMTTRNRS>
<TRNUID>1001
<STATUS>
<CODE>0
<SEVERITY>INFO
</STATUS>
<STMTRS>
<CURDEF>NZD
<BANKACCTFROM>
<BANKID>12
<BRANCHID>1234
<ACCTID>1234567-12
<ACCTTYPE>CHECKING
</BANKACCTFROM>
<BANKTRANLIST>
<DTSTART>20240903
<DTEND>20240903
<STMTTRN>
<TRNTYPE>POS
<DTPOSTED>20240903
<TRNAMT>-12.00
<FITID>2024090301
<NAME>FASTFOOD
<MEMO>EFTPOS
</STMTTRN>
</BANKTRANLIST>
<LEDGERBAL>
<BALAMT>1234.12
<DTASOF>20240903
</LEDGERBAL>
<AVAILBAL>
<BALAMT>1234.12
<DTASOF>20240903
</AVAILBAL>
</STMTRS>
</STMTTRNRS>
</BANKMSGSRSV1>
</OFX>
```

**Comment by pelaxa** [comment]
Try this again.  Hopefully it is fixed now.
